#These are Global Settings for Residence.
Global:
    # This loads the <language>.yml file in the Residence Language folder
    # All Residence text comes from this file. (NOT DONE YET)
    Language: English
    # Stick is the default selection tool for Residence.
    # You can change it to another item ID listed here: http://www.minecraftwiki.net/wiki/Data_values
    SelectionToolId: 280
    # This determins which tool you can use to see info on residences, default is String.
    # Simply equip this tool and hit a location inside the residence and it will display the info for it.
    InfoToolId: 287
    # The interval, in milliseconds, between movement checks.
    # Reducing this will increase the load on the server.
    # Increasing this will allow players to move further in movement restricted zones before they are teleported out.
    MoveCheckInterval: 500
    # The interval, in minutes, between residence saves.
    SaveInterval: 10
    # The default group to use if Permissions fails to attach or your not using Permissions.
    DefaultGroup: default
    # Enable / Disable the Lease System.
    UseLeaseSystem: false
    # The interval, in minutes, between residence lease checks (if leases are enabled).
    LeaseCheckInterval: 10
    # Allows leases to automatically renew so long as the player has the money, if economy is disabled, this setting does nothing.
    LeaseAutoRenew: true
    # Whether or not to use the Permissions system in conjunction with this config.
    EnablePermissions: true
    # Set to true if NOT using Permissions or PermissionsBukkit, or using a really old version of Permissions
    LegacyPermissions: false
    # Enable / Disable Residence's Economy System (iConomy, MineConomy, Essentials, BOSEconomy, and RealEconomy supported).
    EnableEconomy: true
    # Enables or disables the Rent System
    EnableRentSystem: false
    # The interval, in minutes, between residence rent expiration checks (if the rent system is enabled).
    RentCheckInterval: 10
    # Enable or disable residence chat channels.
    ResidenceChatEnable: true
    # True for ActionBar - new component in 1.8
    # False for old Messaging in chat enter/leave Residence messages
    UseActionBar: true
    # Color of residence chat.
    ResidenceChatColor: DARK_PURPLE
    # Whether or not to ignore the usual Permission flags and only allow OPs and groups with 'residence.admin' to change residences.
    AdminOnlyCommands: false
    # Setting this to true makes server OPs admins.
    AdminOPs: true
    # This is the name of the plugin you use for multiworld, if you dont have a multiworld plugin you can safely ignore this.
    # The only thing this does is check to make sure the multiworld plugin is enabled BEFORE Residence, to ensure properly loading residences for other worlds.
    MultiWorldPlugin: Multiverse-Core
    # Setting this to true causes subzones to inherit flags from their parent zones.
    ResidenceFlagsInherit: true
    # Setting this to false will allow rented residences to be modified by the renting player.
    PreventRentModify: true
    # Setting this to false will cause residence to continue to load even if a error is detected in the save file.
    StopOnSaveFault: true
    # This is the residence name filter, that filters out invalid characters.  Google "Java RegEx" or "Java Regular Expressions" for more info on how they work.
    ResidenceNameRegex: '[^a-zA-Z0-9\\-\\_]'
    # Setting this to true sends a message to the console every time Residence does a rent expire check or a lease expire check.
    ShowIntervalMessages: false
    # Check for new version when server start and connect OP. 
    VersionCheck: true
    # Experimental - The following settings are lists of block IDs to be used as part of the checks for the "container" and "use" flags when using mods.
    CustomContainers: []
    CustomBothClick: []
    CustomRightClick: []
